### ISSUE TITLE
Directory Sync

### ISSUE THREAD

**Issue by jaytaylor** [russss/Herd#26]
This works great for syncing individual files.  Is there a way to efficiently transfer the contents of an entire directory?

**Comment by russss** [comment]
I believe BitTorrent isn't great for transferring lots of small files, so the recommended procedure is to tar the directory up and then transfer the tarball using BitTorrent/Herd. This will also give you the advantage of compression across the entire file.

**Comment by jaytaylor** [comment]
roger that, thanks!
